-- Create databases
CREATE DATABASE $(MSSQL_DB);
CREATE DATABASE $(MSSQL_DB_SHADOW);
GO
-- Setup users
CREATE LOGIN $(MSSQL_USER) WITH PASSWORD = '$(MSSQL_PASSWORD)';
GO
CREATE USER $(MSSQL_USER) FOR LOGIN $(MSSQL_USER);
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_USER)];
GO
